#!/bin/sh

num_cpus=$(grep -c processor /proc/cpuinfo)
[ "$num_cpus" != 0 ] || num_cpus=1

threads=$((num_cpus * 4))
last_thread=$((threads - 1))
FACTOR=200

[ -f /etc/sysconfig/zram ] && source /etc/sysconfig/zram || true
factor=$FACTOR # percentage

memtotal=$(grep MemTotal /proc/meminfo | awk ' { print $2 } ')
mem_by_cpu=$(($memtotal/$threads*$factor/100*1024))
modprobe -q zram num_devices=$threads
for i in $(seq 0 $last_thread); do
  #enable lz4 if that supported
  grep -q lz4 /sys/block/zram$i/comp_algorithm && echo lz4 > /sys/block/zram$i/comp_algorithm
  echo $mem_by_cpu > /sys/block/zram$i/disksize
  mkswap /dev/zram$i
  swapon -p 100 /dev/zram$i
done

echo 100 > /proc/sys/vm/swappiness
echo 15 > /proc/sys/vm/dirty_ratio
echo 3 > /proc/sys/vm/dirty_background_ratio
echo 100000 > /proc/sys/vm/vfs_cache_pressure
