#!/bin/bash

num_cpus=$(grep -c processor /proc/cpuinfo)
[ "$num_cpus" != 0 ] || num_cpus=1

last_cpu=$((num_cpus - 1))

for i in $(seq 0 $last_cpu); do
	compr=$(< "/sys/block/zram$i/compr_data_size")
	orig=$(< "/sys/block/zram$i/orig_data_size")
	ratio=0
	if [ $compr -gt 0 ]; then
		ratio=$(echo "scale=2; $orig*100/$compr" | bc -q)
	fi
	echo -e "/dev/zram$i:\t$ratio% ($orig -> $compr)"
done
