#!/bin/sh

function getKernelMajorVersion() {
        head -c 1 /proc/sys/kernel/osrelease
}

ls /sys/block/zram* > /dev/null 2>&1 || exit 0

for i in /sys/block/zram*; do
	if [ $(getKernelMajorVersion) -gt 3 ]; then
		compr=$(cat $i/mm_stat | awk '{ print $2 }')
		orig=$(cat $i/mm_stat | awk '{ print $1 }')
	else
	        compr=$(< $i/compr_data_size)
	        orig=$(< $i/orig_data_size)
	fi

	ratio=0
	if [ $compr -gt 0 ]; then
		ratio=$(echo "scale=2; $orig*100/$compr" | bc -q)
	fi
	echo -e "/dev/${i/*\/}:\t$ratio% ($orig -> $compr)"
done
